#!/bin/bash
export PATH=ONAME/sys_enhance/bin:$PATH
export PYTHONPATH=ONAME/sys_enhance/lib/python27.zip:ONAME/sys_enhance/bin/lib/python2.7:ONAME/sys_enhance/lib/python2.7/plat-linux2:ONAME/sys_enhance/lib/python2.7/lib-tk:ONAME/sys_enhance/lib/python2.7/lib-old:ONAME/sys_enhance/lib/python2.7/lib-dynload:ONAME/sys_enhance/lib/python2.7/site-packages
export MANPATH=ONAME/sys_enhance/share/man:$MANPATH
export LD_LIBRARY_PATH=ONAME/sys_enhance/lib:ONAME/sys_enhance/lib64:$LD_LIBRARY_PATH
export LIBRARY_PATH=ONAME/sys_enhance/lib:ONAME/sys_enhance/lib64:$LIBRARY_PATH
export CPATH=ONAME/sys_enhance/include:$CPATH
